-- ATIVAR O BANCO DE DADOS
USE escola_vinicius;

-- APAGAR TABELAS SE JÁ EXISTIREM
DROP TABLE IF EXISTS REGISTRO_ESCOLAR_PROFESSOR;
DROP TABLE IF EXISTS REGISTRO_ESCOLAR_ALUNO;
DROP TABLE IF EXISTS SECRETARIA, DIRETORIA, ALUNO, ALUNOS, PROFESSOR;

-- TABELAS
CREATE TABLE SECRETARIA (
    ID_SECRETARIA INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE DIRETORIA (
    ID_DIRETORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    ESTADO_CIVIL ENUM('Solteiro', 'Casado', 'Divorciado', 'Viúvo') DEFAULT 'Solteiro',
    SALARIO DECIMAL(10,2) NOT NULL,
    CURRICULO VARCHAR(500),
    ACESSOS VARCHAR(100),
    REGISTRO_ALUNOS_E_PROFESSORES VARCHAR(255),
    CONTROLE_DE_FREQUENCIA VARCHAR(255),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ALUNO (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REGISTRO_ESCOLAR_ALUNO (
    ID_REGISTRO_ESCOLAR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    RG VARCHAR(20) NOT NULL,
    RA VARCHAR(20) NOT NULL UNIQUE,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SEDE_DO_ALUNO ENUM('Sede Central', 'Sede Norte', 'Sede Sul') NOT NULL,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    RELATORIOS VARCHAR(255),
    BOLETIM VARCHAR(255),
    DESEMPENHO_ESCOLAR VARCHAR(255),
    ID_ALUNO INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO) ON DELETE CASCADE
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REGISTRO_ESCOLAR_PROFESSOR (
    ID_REGISTRO_ESCOLAR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    ESTADO_CIVIL ENUM('Solteiro', 'Casado', 'Divorciado', 'Viúvo') DEFAULT 'Solteiro',
    SALARIO DECIMAL(10,2) NOT NULL,
    CURRICULO VARCHAR(500),
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ativo'

);
CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REGISTRO_ESCOLAR_PROFESSOR (
    ID_REGISTRO_ESCOLAR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    ESTADO_CIVIL ENUM('Solteiro', 'Casado', 'Divorciado', 'Viúvo') DEFAULT 'Solteiro'
);
DROP TABLE IF EXISTS REGISTRO_ESCOLAR_PROFESSOR;
-- VISUALIZAR TABELAS
SHOW TABLES;

-- ALTERAÇÕES DE ESTRUTURA (SECRETARIA)
ALTER TABLE SECRETARIA ADD EMAIL VARCHAR(100);
ALTER TABLE SECRETARIA ADD DIRETORIA VARCHAR(50);
ALTER TABLE SECRETARIA MODIFY DIRETORIA DECIMAL(10,2);
ALTER TABLE SECRETARIA DROP COLUMN EMAIL;

-- RENOMEAR TABELA (Apenas uma vez)
RENAME TABLE ALUNO TO ALUNOS;

-- APAGAR DADOS DE UMA TABELA (Com bypass de Foreign Key)
SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE ALUNOS;
SET FOREIGN_KEY_CHECKS = 1;

-- INSERIR ALUNOS
INSERT INTO ALUNOS (ID_ALUNO) VALUES (DEFAULT);
INSERT INTO ALUNOS (ID_ALUNO) VALUES (DEFAULT);
INSERT INTO ALUNOS (ID_ALUNO) VALUES (DEFAULT);

-- CONSULTAR DADOS NA DIRETORIA
SELECT * FROM DIRETORIA;

-- INSERIR PROFESSORES PARA GERAR ID_PROFESSOR
INSERT INTO PROFESSOR VALUES (DEFAULT), (DEFAULT), (DEFAULT), (DEFAULT), (DEFAULT);

-- INSERIR DADOS EM REGISTRO_ESCOLAR_PROFESSOR (Valores únicos ajustados)
INSERT INTO REGISTRO_ESCOLAR_PROFESSOR ( ID_REGISTRO_ESCOLAR, NOME, RG, CPF, EMAIL, ESTADO_CIVIL
) VALUES 
(default,'Professor 1', '1111111', '111.111.111-11', 'prof1@gmail.com', 'Solteiro'),
(default,'Professor 2', '2222222', '222.222.222-22', 'prof2@gmail.com', 'Solteiro'),
(default,'Professor 3', '3333333', '333.333.333-33', 'prof3@gmail.com', 'Solteiro'),
(default,'Professor 4', '4444444', '444.444.444-44', 'prof4@gmail.com', 'Solteiro'),
(default,'Professor 5', '5555555', '555.555.555-55', 'prof5@gmail.com','Solteiro');


-- CONSULTAR PROFESSORES
SELECT * FROM REGISTRO_ESCOLAR_PROFESSOR;

TRUNCATE TABLE REGISTRO_ESCOLAR_PROFESSOR;
