CREATE DATABASE mecanica;
USE mecanica;

CREATE TABLE FUNCIONARIO (
    ID_funcionario INT AUTO_INCREMENT PRIMARY KEY,
    cargo_funcionario VARCHAR(50),
    cpf_do_funcionario VARCHAR(14),
    nome_de_funcionario VARCHAR(100),
    Salario DECIMAL(10,2),
    telefone VARCHAR(20), 
    email VARCHAR(100)
);

CREATE TABLE PAGAMENTO (
    ID_pagamento INT AUTO_INCREMENT PRIMARY KEY,
    recebimento VARCHAR(20),
    debito VARCHAR(50),
    credito VARCHAR(50),
    pix VARCHAR(50),
    papel VARCHAR(50)
);

CREATE TABLE CLIENTE (
    ID_cliente INT AUTO_INCREMENT PRIMARY KEY,
    telefone VARCHAR(20),
    nome VARCHAR(100),
    email VARCHAR(100),
    CPF VARCHAR(14),
    cidade VARCHAR(40)
);

CREATE TABLE VEICULOS (
    ID_VEICULOS INT AUTO_INCREMENT PRIMARY KEY,
    caminhao VARCHAR(50),
    carro VARCHAR(50),
    moto VARCHAR(50),
    vans VARCHAR(50),
    tipo VARCHAR(50)
);

CREATE TABLE MARCA (
    ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    ANO INT, 
    FABRICACAO VARCHAR(100),
    estilo VARCHAR(50),
    CONTRATO VARCHAR(50),
    veiculos VARCHAR(255),
    itens VARCHAR(255)
);

CREATE TABLE FORNECEDOR (
    ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    TELEFONE VARCHAR(20), 
    FABRICACAO VARCHAR(100),
    MARCA VARCHAR(50),
    CONTRATO VARCHAR(50),
    EMAIL VARCHAR(255),
    itens VARCHAR(255),
    VALIDADE VARCHAR(200)
);

CREATE TABLE PECAS (
    ID_PECAS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    QUANTIDADE INT, 
    FABRICACAO VARCHAR(100),
    MARCA VARCHAR(50),
    VALIDADE VARCHAR(200)
);

CREATE TABLE SERVIÇOS (
    ID_SERVICOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    QUANTIDADE INT,
    PLANO VARCHAR(100),
    VALOR DECIMAL(10,2), 
    TELEFONE VARCHAR(200),
    EMAIL VARCHAR(200)
);

CREATE TABLE ORDENS_SERVIÇOS (
    ID_ORDEM INT AUTO_INCREMENT PRIMARY KEY, 
    NOME VARCHAR(100),
    PROBLEMAS VARCHAR(100),
    VALOR DECIMAL(10,2),
    TELEFONE VARCHAR(200),
    EMAIL VARCHAR(200)
);

CREATE TABLE MODELOS (
    ID_MODELOS INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100),
    PAIS VARCHAR(100),
    COR VARCHAR(50),
    PLACA VARCHAR(200),
    ESTILO VARCHAR(200)
);

ALTER TABLE CLIENTE ADD CASA VARCHAR(50);
ALTER table FUNCIONARIO ADD ENDEREÇO VARCHAR(50);
ALTER TABLE PAGAMENTO ADD COMPROVANTE varchar(50);
ALTER TABLE VEICULOS ADD  TEMPOUSO DATETIME;
ALTER TABLE MARCA ADD CIDADE VARCHAR(90);
ALTER TABLE FORNECEDOR ADD TRANSPORTADORA VARCHAR(90);
ALTER TABLE PECAS ADD RESPONSAVEL VARCHAR(80);
ALTER TABLE SERVIÇOS ADD TEMPO DATETIME;
ALTER TABLE ORDENS_SERVIÇOS ADD RECONHECIMENTO VARCHAR(70);
ALTER TABLE MODELOS ADD RESPONSAVEL VARCHAR(50);


ALTER TABLE CLIENTE DROP column CASA;
ALTER table FUNCIONARIO DROP column ENDEREÇO ;
ALTER TABLE PAGAMENTO DROP column COMPROVANTE;
ALTER TABLE VEICULOS DROP column  TEMPOUSO;
ALTER TABLE MARCA DROP column CIDADE;
ALTER TABLE FORNECEDOR DROP column TRANSPORTADORA;
ALTER TABLE PECAS DROP column RESPONSAVEL;
ALTER TABLE SERVIÇOS DROP column TEMPO;
ALTER TABLE ORDENS_SERVIÇOS DROP column RECONHECIMENTO;
ALTER TABLE MODELOS DROP column RESPONSAVEL;
