-- COMANDO PARA CRIAR BANCO DE DADOS
CREATE DATABASE ESCOLA_VINICIUS;
CREATE DATABASE ESCOLA_VINICIUS2;

-- COMANDO PARA APAGAR BANCO DE DADOS
DROP DATABASE escola_vinicius2;

-- COMANDO PARA ATIVAR BANCO DE DADOS
USE ESCOLA_VINICIUS;

-- COMANDO PARA CRIAR TABELAS
USE ESCOLA_VINICIUS;

CREATE TABLE SECRETARIA (
    ID_SECRETARIA INT AUTO_INCREMENT PRIMARY KEY
);
CREATE TABLE DIRETORIA (
    ID_DIRETORIA INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    ESTADO_CIVIL VARCHAR(30),
    SALARIO DECIMAL(10,2) NOT NULL,
    CURRICULO VARCHAR(500),
    ACESSOS VARCHAR(100),
    REGISTRO_ALUNOS_E_PROFESSORES VARCHAR(255),
    CONTROLE_DE_FREQUENCIA VARCHAR(255),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ALUNO (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REGISTRO_ESCOLAR_ALUNO (
    ID_REGISTRO_ESCOLAR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    RG VARCHAR(20) NOT NULL,
    RA VARCHAR(20) NOT NULL UNIQUE,
    DATA_DE_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    SEDE_DO_ALUNO VARCHAR(60) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    RELATORIOS VARCHAR(255),
    BOLETIM VARCHAR(255),
    DESEMPENHO_ESCOLAR VARCHAR(255),
    ID_ALUNO INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO(ID_ALUNO) ON DELETE CASCADE
);

CREATE TABLE PROFESSOR (
    ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE REGISTRO_ESCOLAR_PROFESSOR (
    ID_REGISTRO_ESCOLAR INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(60) NOT NULL,
    RG VARCHAR(20) NOT NULL,
    CPF VARCHAR(14) NOT NULL UNIQUE,
    EMAIL VARCHAR(60) NOT NULL UNIQUE,
    ESTADO_CIVIL VARCHAR(30),
    SALARIO DECIMAL(10,2) NOT NULL,
    CURRICULO VARCHAR(500),
    STATUS VARCHAR(10) NOT NULL DEFAULT 'ativo',
    LOGIN VARCHAR(50) NOT NULL UNIQUE,
    ALUNOS_BOLETIM VARCHAR(255),
    RELATORIOS_DE_CLASSE VARCHAR(255),
    PRESENCA INT,
    MATERIAL_DE_ESTUDO VARCHAR(255),
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE DICIPLINAS (
    ID_DICIPLINAS INT AUTO_INCREMENT PRIMARY KEY,
    AULAS INT NOT NULL,
    ATIVIDADES VARCHAR(255),
    AVALIACOES VARCHAR(255),
    CONHECIMENTO VARCHAR(255)
);
